        !COMPILER-GENERATED INTERFACE MODULE: Fri Aug 09 18:38:17 2019
        ! This source file is for reference only and may not completely
        ! represent the generated interface used by the compiler.
        MODULE CONVERTDISCRVERT__genmod
          INTERFACE 
            SUBROUTINE CONVERTDISCRVERT(SWDISCRVERT,PART,SWOP,NRLEVS,   &
     &NUMLAY,BOTCOM,NUMNOD,DZ,H,THETA,INQ,INQROT,INQDRA,ITHETABEG,TSOIL,&
     &COFGEN,NUMNODNEW,DZNEW,BOTCOMNEW,HNEW,THETANEW,INQNEW,INQROTNEW,  &
     &INQDRANEW,ITHETABEGNEW,TSOILNEW,DIPOCP,FRARMTRX,IAVFRMPWLWTDM1,   &
     &IAVFRMPWLWTDM2,IQEXCMTXDM1CP,IQEXCMTXDM2CP,IQOUTDRRAPCP,VLMPSTDM1,&
     &VLMPSTDM2,DIPOCPNEW,IAVFRMPWLWTDM1NEW,IAVFRMPWLWTDM2NEW,          &
     &IQEXCMTXDM1CPNEW,IQEXCMTXDM2CPNEW,IQOUTDRRAPCPNEW,VLMPSTDM1NEW,   &
     &VLMPSTDM2NEW,SWSOPHY,NUMTAB,SPTAB)
              INTEGER(KIND=4) :: SWDISCRVERT
              INTEGER(KIND=4) :: PART
              INTEGER(KIND=4) :: SWOP
              INTEGER(KIND=4) :: NRLEVS
              INTEGER(KIND=4) :: NUMLAY
              INTEGER(KIND=4) :: BOTCOM(200)
              INTEGER(KIND=4) :: NUMNOD
              REAL(KIND=8) :: DZ(5000)
              REAL(KIND=8) :: H(5000)
              REAL(KIND=8) :: THETA(5000)
              REAL(KIND=8) :: INQ(5001)
              REAL(KIND=8) :: INQROT(5000)
              REAL(KIND=8) :: INQDRA(5,5000)
              REAL(KIND=8) :: ITHETABEG(5000)
              REAL(KIND=8) :: TSOIL(0:5000)
              REAL(KIND=8) :: COFGEN(12,5000)
              INTEGER(KIND=4) :: NUMNODNEW
              REAL(KIND=8) :: DZNEW(5000)
              INTEGER(KIND=4) :: BOTCOMNEW(200)
              REAL(KIND=8) :: HNEW(5000)
              REAL(KIND=8) :: THETANEW(5000)
              REAL(KIND=8) :: INQNEW(5001)
              REAL(KIND=8) :: INQROTNEW(5000)
              REAL(KIND=8) :: INQDRANEW(5,5000)
              REAL(KIND=8) :: ITHETABEGNEW(5000)
              REAL(KIND=8) :: TSOILNEW(0:5000)
              REAL(KIND=8) :: DIPOCP(5000)
              REAL(KIND=8) :: FRARMTRX(5000)
              REAL(KIND=8) :: IAVFRMPWLWTDM1(5000)
              REAL(KIND=8) :: IAVFRMPWLWTDM2(5000)
              REAL(KIND=8) :: IQEXCMTXDM1CP(5000)
              REAL(KIND=8) :: IQEXCMTXDM2CP(5000)
              REAL(KIND=8) :: IQOUTDRRAPCP(5000)
              REAL(KIND=8) :: VLMPSTDM1(5000)
              REAL(KIND=8) :: VLMPSTDM2(5000)
              REAL(KIND=8) :: DIPOCPNEW(5000)
              REAL(KIND=8) :: IAVFRMPWLWTDM1NEW(5000)
              REAL(KIND=8) :: IAVFRMPWLWTDM2NEW(5000)
              REAL(KIND=8) :: IQEXCMTXDM1CPNEW(5000)
              REAL(KIND=8) :: IQEXCMTXDM2CPNEW(5000)
              REAL(KIND=8) :: IQOUTDRRAPCPNEW(5000)
              REAL(KIND=8) :: VLMPSTDM1NEW(5000)
              REAL(KIND=8) :: VLMPSTDM2NEW(5000)
              INTEGER(KIND=4) :: SWSOPHY
              INTEGER(KIND=4) :: NUMTAB(5000)
              REAL(KIND=8) :: SPTAB(5,5000,1000)
            END SUBROUTINE CONVERTDISCRVERT
          END INTERFACE 
        END MODULE CONVERTDISCRVERT__genmod
