        !COMPILER-GENERATED INTERFACE MODULE: Fri Aug 09 18:40:54 2019
        ! This source file is for reference only and may not completely
        ! represent the generated interface used by the compiler.
        MODULE MACRORATE__genmod
          INTERFACE 
            SUBROUTINE MACRORATE(ITASK,ICPBTDM,ICPBTPERZON,ICPSATGWL,   &
     &ICPSATPEGWL,ICPTPPERZON,ICPTPSATZON,ICPTPWASRDM,ARMPSSDM,AWLCORFAC&
     &,FRMPWALWET,KDCRRLREF,SORPDMCP,THTSRPREFDMCP,TIMABSCUMDMCP,VLMPDM,&
     &VLMPDMCP,WASRMP,WASRMPDM,ZBTDM,ZWALEVDM,FLDRATUB,FLENDSRPEVT,     &
     &QEXCMTXDMCP,QININTSATDMCP,QINMTXSATDMCP,QINTOPLATDM,QINTOPPREDM,  &
     &QOUTDRRAPCP,QOUTMTXSATDMCP,QOUTMTXUNSDMCP)
              INTEGER(KIND=4) :: ITASK
              INTEGER(KIND=4) :: ICPBTDM(20)
              INTEGER(KIND=4) :: ICPBTPERZON
              INTEGER(KIND=4) :: ICPSATGWL
              INTEGER(KIND=4) :: ICPSATPEGWL
              INTEGER(KIND=4) :: ICPTPPERZON
              INTEGER(KIND=4) :: ICPTPSATZON
              INTEGER(KIND=4) :: ICPTPWASRDM(20)
              REAL(KIND=8) :: ARMPSSDM(20)
              REAL(KIND=8) :: AWLCORFAC(5000)
              REAL(KIND=8) :: FRMPWALWET(20,5000)
              REAL(KIND=8) :: KDCRRLREF(5)
              REAL(KIND=8) :: SORPDMCP(20,5000)
              REAL(KIND=8) :: THTSRPREFDMCP(20,5000)
              REAL(KIND=8) :: TIMABSCUMDMCP(20,5000)
              REAL(KIND=8) :: VLMPDM(20)
              REAL(KIND=8) :: VLMPDMCP(20,5000)
              REAL(KIND=8) :: WASRMP
              REAL(KIND=8) :: WASRMPDM(20)
              REAL(KIND=8) :: ZBTDM(20)
              REAL(KIND=8) :: ZWALEVDM(20)
              LOGICAL(KIND=4) :: FLDRATUB(5)
              LOGICAL(KIND=4) :: FLENDSRPEVT(20,5000)
              REAL(KIND=8) :: QEXCMTXDMCP(20,5000)
              REAL(KIND=8) :: QININTSATDMCP(20,5000)
              REAL(KIND=8) :: QINMTXSATDMCP(20,5000)
              REAL(KIND=8) :: QINTOPLATDM(20)
              REAL(KIND=8) :: QINTOPPREDM(20)
              REAL(KIND=8) :: QOUTDRRAPCP(5000)
              REAL(KIND=8) :: QOUTMTXSATDMCP(20,5000)
              REAL(KIND=8) :: QOUTMTXUNSDMCP(20,5000)
            END SUBROUTINE MACRORATE
          END INTERFACE 
        END MODULE MACRORATE__genmod
