@echo off
rem part of FieldStudies distributed with SWAP4
del/q  result.crp
del/q  result.irg
del/q   *.aun
del/q   *.afo
del/q   *.bfo
del/q   *.blc
del/q   *.bak
del/q   *.bal
del/q   *.bun
del/q   *.csv
del/q   *.dat
del/q   *.drf
del/q   *.dwb
del/q   *.end
del/q   *.inc
del/q   *.log
del/q   *.man
del/q   *.out
del/q   *.png
del/q   *.res
del/q   *.rot
del/q   *.sba
del/q   *.snw
del/q   *.str
del/q   *.swb
del/q   *.tem
del/q   *.tmp
del/q   *.vap
del/q   *.wba
del/q   swap.ok
rem exit
