#--- R SAMUCA
#--- MDSV - Sep/2019

SimMet.SWAP  = function(SC.set.fn,
                    met.dt.fn,
                    SC.outpath,
                    SC.outfn){
  
  #--------------------------------------------------------#
  #------ Create Meteorological File for SAMUCA -----------#
  #--------------------------------------------------------#
  #   SC.template.fn  Control File Template "Path\\name.ctl"
  #   C.set.fn        Control File Settings "Path\\file.csv"
  #   SC.outpath      Output Control File Path
  #   SC.outfn        Output Control Filename
  #
  #   -Settings.csv
  #   File .csv must contain 7 columns:
  #   find      target string on template
  #   rep       replacement value
  #   justify   justify format (r = right, l = left, c = centre)
  #   width     character size of replecement
  #   type      type of value (c = character, i = integer, r = real) Note: Logical = character
  #   digits    maximun number of digits including character (More info in: ?format())
  #   nsmall    minimun number of digits
  #--------------------------------------------------------#
  
  #if(missing(SC.template.fn)){stop("Argument SC.template.fn is missing for SimControl function")}
  if(missing(SC.set.fn)){stop("Argument SC.set.fn is missing for SimControl function")}
  if(missing(SC.outpath)){stop("Argument SC.outpath is missing for SimControl function")}
  if(missing(SC.outfn)){stop("Argument SC.outfn is missing for SimControl function")}
  
  #--- Read Template Settings file (csv)
  SC.set      = read.csv(SC.set.fn, as.is = T)
  
  #--- Template header
  SC.template =c(
  "* Source of data    : <prj.nm> - <site.nm>",
  "* File content      : Input weather file for Swap 3.2 (www.swap.alterra.nl)",
  "* File generated by : R-Script ",
  "* File generated at : <date_now>")
  
  #--- Set Column width and SAMUCA's meteorological variables and order
  swap.met.order = c("station","dd","mm","yyyy","srad_kj","tmin","tmax","rain","wind","ea","etref")
  real.col = c("srad_kj","tmin","tmax","rain","wind","ea","etref")
  
  #--- include date
  SC.template = gsub("<date_now>",format(Sys.Date(), "%d-%b-%Y"),SC.template)
  SC.template = gsub("<prj.nm>",SC.set$rep[SC.set$find == "<prj.nm>"],SC.template)
  SC.template = gsub("<site.nm>",SC.set$rep[SC.set$find == "<site.nm>"],SC.template)
  
  #--- Read meteorological data
  met.dt      = read.csv(met.dt.fn, as.is = T)
  
  #--- Add project name as station name
  met.dt$station = paste0("\'",SC.set$rep[SC.set$find == "<prj.nm>"],"\'")
  
  #--- Order to swap template
  met.dt.swap  = met.dt[,swap.met.order]
  
  #--- Add "." to real values
  for(c in real.col){
    met.dt.swap[,c] = format(as.numeric(met.dt.swap[,c]), nsmall = 1, digits = 2)
  }
  
  #--- rename to swap's variable names
  colnames(met.dt.swap) = c("station","DD","MM","YYYY","Rad","Tmin","Tmax","Rain","Wind","Hum","etref")
  
  #--- number of years
  l.yr = unique(met.dt.swap$YYYY)
  
  for(yr in l.yr){
    
    yr.lab = substr(as.character(yr),2,4)
    
    write(SC.template,file = paste0(SC.outpath,"\\",SC.outfn,".",yr.lab))
    
    write.fwf(met.dt.swap[met.dt.swap$YYYY == yr,],
              file = paste0(SC.outpath,"\\",SC.outfn,".",yr.lab),
              sep = ",",
              colnames = T,
              append = T)
    
  }
}
